### ISSUE TITLE
Exclude maven targets

### ISSUE THREAD

**Issue by o-schneider** [cluelessjoe/javaPackagePrivateWat#1]
:D

**Comment by cluelessjoe** [comment]
Thanks my dear :) Even a .gitignore was added for, I hope you like it :)

**Comment by o-schneider** [comment]
Very good ! Awesome fix. I like it soooo much !!! :+1:

**Comment by cluelessjoe** [comment]
Sometimes I wonder what you take ^^

**Comment by o-schneider** [comment]
My guess is you don't really wanna know...
